backend = "xrender"
rules = (
	{ match = "!focused"; opacity = 0.85; }
)
animations = (
	{
		triggers = ["increase-opacity"];

		opacity = {
			duration = 0.1;
			start = 0.85;
			end = 1;
		};
	},
	{
		triggers = ["decrease-opacity"];

		opacity = {
			duration = 0.1;
			start = 1;
			end = 0.85;
		};
	}
)
